### ISSUE TITLE
Force close on host when play/pausing on guest with empty playlist

### ISSUE THREAD

**Issue by theJenix** [TheLastCrusade/SoundStream#171]
Steps to reproduce:
1. Launch app on host device
2. Launch app on guest device
3. Press "create" on host device
4. Press "join" on guest device
5. After dialog appears on host, select only the guest device and click ok.  Wait until the music library is displayed on the guest with the drawer open.
6. Close the drawer on the guest device.
7. Without adding any music, press play on the guest device.

This may crash the app immediately, or it may show the "Playlist is empty" message on the host.  If it shows the message:
8. Observe that the playbar shows a pause button the guest.
9. Press pause.
10. Observe the app crash on the host.

**Comment by theJenix** [comment]
Test in conjunction with 3 phone tests.

**Comment by dgreenhalgh** [comment]
@theJenix will validate on Monday

**Comment by theJenix** [comment]
This has been verified to no longer be an issue, but there are some synchronization issues.  These are fixed in pull request #222
