### ISSUE TITLE
Song information missing from lock screen controls on guest device

### ISSUE THREAD

**Issue by theJenix** [TheLastCrusade/SoundStream#172]
Observed on Nexus 7.  Lock screen controls are present, and functional, but the song album and title is missing.

To reproduce:
1. Establish a network, add songs to the playlist, and press play.
2. Lock the guest phone.
3. Press the side button to activate the lock screen.

**Comment by reidbaker** [comment]
I looked at this tonight. It looks like we are listening to a broadcastIntent ACTION_SONG_PLAYING to set the information. We only sent that intent when we call setSong in the SingleFileAudioPlayer. Looks like the best way to fix this is when we receive either a SongStatusMessage or PlayStatusMesssage. Haven't figured out which.

**Comment by reidbaker** [comment]
If anyone has thoughts on this let me know I dont have a good clean fix.
