### ISSUE TITLE
Cannot remove currently playing item on guest

### ISSUE THREAD

**Issue by theJenix** [TheLastCrusade/SoundStream#179]
When you try to remove the currently playing item, the removed item reappears and pops up a toast saying "The playlist is empty.

Observed when performing Test 13b.

**Comment by dgreenhalgh** [comment]
Verify on #178 fix

**Comment by theJenix** [comment]
With pull request #214, I've seen this issue largely go away except when attempting to remove the currently playing item.  To reproduce:

1) establish a network, and add 3 items that live on the host to the playlist (you can add items from anywhere, but adding items that live on the host will be quicker).
2) press play, and skip to the last song.
3) from the guest, swipe to remove the currently playing song.

What I see is it skips to the top of the playlist, but the song that was removed comes back.

**Comment by reidbaker** [comment]
What I see as of now is this only happens for songs on the host device. If the song removed is the guest's song then the song flashes but is removed.

**Comment by theJenix** [comment]
This was fixed in #220, and then the fix was changed slightly in #222.  This issue should get closed along with #222
