### ISSUE TITLE
Partially transfered songs are skipped

### ISSUE THREAD

**Issue by theJenix** [TheLastCrusade/SoundStream#181]
Test 17a/17b do not work as described.  Partially songs are skipped until they are fully transferred.

**Comment by reidbaker** [comment]
Not fixing this until beta is released. This looks like a great premium feature without being necessary.

**Comment by theJenix** [comment]
Created enhancement #292 to track the feature request.  @twrobel3 Can you update the test script to remove 17a/17b from our normal tests and move them to a premium or future features section?  This can be closed after the test script is updated.

**Comment by dgreenhalgh** [comment]
@twrobel3, could you update the test scripts?
