### ISSUE TITLE
When guest disconnects, partially transfered items stay in the playlist

### ISSUE THREAD

**Issue by theJenix** [TheLastCrusade/SoundStream#187]
Observed when executing test 24.

**Comment by reidbaker** [comment]
@theJenix I am having an issue with playlist data manager. How do I tell the data manager to stop tracking a Playlist entry. Look at this branch https://github.com/reidbaker/SoundStream/tree/no_lockscreen_on_guest

**Comment by dgreenhalgh** [comment]
Fixed in #228
