### ISSUE TITLE
Fix the Fixme's in Base Testing Framework

### ISSUE THREAD

**Issue by taywrobel** [TheLastCrusade/SoundStream#219]
There are 3 fixme's in the framework, two have to do with interacting with the bluetooth dialog, and one has to do with asserting if the menu button is active.  I currently don't have the tools to look at the UI in a way that lets me figure out how to handle them, but should be getting it soon.

**Comment by dgreenhalgh** [comment]
![why](https://i.kym-cdn.com/entries/icons/facebook/000/002/085/Kornheiser_Why.jpg)
