### ISSUE TITLE
Lack of third party credit

### ISSUE THREAD

**Issue by reidbaker** [TheLastCrusade/SoundStream#227]
We do not give credit anywhere in our app to the open source projects we use. We cannot release without attribution.

**Comment by dgreenhalgh** [comment]
Is this something that's more appropriate in which of the following:
- The About page
- The Play Store entry
- The source code

You're right, this needs to be cleared up before we push beta

**Comment by reidbaker** [comment]
It can go in the about page under a section titled legal

**Comment by dgreenhalgh** [comment]
This should be quick and can be taken care of later in the week

**Comment by theJenix** [comment]
Fixed in pull request #258
