### ISSUE TITLE
Disband causes app to crash 

### ISSUE THREAD

**Issue by reidbaker** [TheLastCrusade/SoundStream#238]
08-04 13:37:28.061: E/AndroidRuntime(22174): java.util.ConcurrentModificationException
08-04 13:37:28.061: E/AndroidRuntime(22174):    at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
08-04 13:37:28.061: E/AndroidRuntime(22174):    at com.lastcrusade.soundstream.service.ConnectionService.disconnectAllGuests(ConnectionService.java:422)

**Comment by theJenix** [comment]
Closed with pull request #253
