### ISSUE TITLE
No way to view first time use instructions again

### ISSUE THREAD

**Issue by DeltaWhy** [TheLastCrusade/SoundStream#303]
Device: Nexus 4 running Android 4.3 (rooted)

For some reason the soft keyboard popped up when I first opened the app. When I closed it, the popup with the first-time use instructions also closed (not sure if this is a bug or if I accidentally double-tapped back). There should be a way to view the instructions again - maybe on the About screen?

**Comment by reidbaker** [comment]
@DeltaWhy I included this issue as part of another issue we have our designer working on. Thanks for the feedback

**Comment by reidbaker** [comment]
@DeltaWhy this is fixed in master
