### ISSUE TITLE
X in the searchbar

### ISSUE THREAD

**Issue by ejohnson44** [TheLastCrusade/SoundStream#324]
The X in the searchbar should close the search, not simply clear the term

**Comment by ejohnson44** [comment]
This appears to not actually be possible due to a bug in actual android code. The on close listener that is provided does not work. There are some hacky work arounds that may or may not work for what we want that are listed here: http://stackoverflow.com/questions/9327826/searchviews-oncloselistener-doesnt-work

**Comment by dgreenhalgh** [comment]
This doesn't seem feasible - at least in the short term - so we'll adjust our expected behavior so that the X in the searchbar simply clears the search term.
