### ISSUE TITLE
Search Results Counter

### ISSUE THREAD

**Issue by ejohnson44** [TheLastCrusade/SoundStream#326]
This can wait until later, but it would be nice to have a results counter on the search - this can be located at the top of the list of returned results, much like the gmail app shows search results - image to come later

**Comment by ejohnson44** [comment]
![2013-12-16 23 17 16](https://f.cloud.github.com/assets/2375000/1761520/3f40e144-66d2-11e3-89c0-95ded71c710e.jpg)

**Comment by dgreenhalgh** [comment]
:+1:

**Comment by reidbaker** [comment]
This is in as of pull request #336
