### ISSUE TITLE
Now playing text incorrect color

### ISSUE THREAD

**Issue by reidbaker** [TheLastCrusade/SoundStream#341]
![playbar](https://f.cloud.github.com/assets/1063596/2172390/ac57d866-9592-11e3-9a4d-d0557c471089.png)

**Comment by dgreenhalgh** [comment]
@ejohnson44, do you know why this may have changed? 

Also, @reidbaker posted this screenshot from Australia

**Comment by reidbaker** [comment]
It happened when I moved us from action bar Sherlock. That being said I need LJ to figure out what color it should be.

**Comment by dgreenhalgh** [comment]
Fixed in #348.
