### ISSUE TITLE
Siding menu frozen after connect from tablet

### ISSUE THREAD

**Issue by reidbaker** [TheLastCrusade/SoundStream#343]
After a tablet connects as a guest nothing in the menu is clickable.

**Comment by dgreenhalgh** [comment]
Have you tested this on multiple tablets, or just yours?

**Comment by reidbaker** [comment]
I have only tested it on a nexus 7 running 4.3. I wanted to listen to steamed music at work today. Do not know if this is tablet related. Rotation fixed the unclickable menu

**Comment by dgreenhalgh** [comment]
@ejohnson44, could you diagnose this and then pass it off to @reidbaker?

**Comment by reidbaker** [comment]
No longer happens on search branch

**Comment by dgreenhalgh** [comment]
Do we know what changed here?

**Comment by reidbaker** [comment]
Not confident but think it was broken because search was broken
